sensor: Add sensor spec files for webserver
Mini-air-quality-station/sensors-and-screen-controller pull request #2
Opened 2023-04-05 07:23 UTC by punfil

Feature sensor spec files
They will be used for webserver to display capabilities of the particular sensor to allow measure frequency adjustment.

Signed-off-by: Wojciech Panfil <wojtek.panfil@hotmail.com>

2023-04-05 15:56 UTC, iwanicki92 requested changes
You should correct couple of things.

<b>sensor_specs/humidity_sensor.yaml:</b>
Humidity sensor measurement unit: %

<b>sensor_specs/particles_sensor.yaml</b>
Particle sensor measurement unit: μg/m<sup>3</sup>, we should probably use proper symbols if we can(μ instead of u). And if you read file are you going to know that 3 means cubed?

<b>sensor_specs/pressure_sensor.yaml</b>
Pressure sensor: BMP280

<b>sensor_specs/temperature_sensor.yaml</b>
Temperature sensor measurement unit: °C

2023-04-05 16:55 UTC, iwanicki92 approved these changes, later dismissed

2023-04-06 20:36 UTC, punfil commented on sensor_specs/temperature_sensor.yaml
> +    active: true
TODO: Active temperature sensor should be DHT22

2023-04-27 14:18 UTC, esesyn01 approved these changes
LGTM

2023-04-27 14:25 UTC, merged